// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArH4FWPnCchcElsxaQPEHfbc-ThknUbu0',
    appId: '1:788378481654:web:4721864d7c920f4db68dd7',
    messagingSenderId: '788378481654',
    projectId: 'customerapp-3c30f',
    authDomain: 'customerapp-3c30f.firebaseapp.com',
    storageBucket: 'customerapp-3c30f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqO-_yBGHvRbZi9XZiY1qOwBOdVPfESBs',
    appId: '1:788378481654:android:0de132d26648fdf8b68dd7',
    messagingSenderId: '788378481654',
    projectId: 'customerapp-3c30f',
    storageBucket: 'customerapp-3c30f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwxRf0hhnjKNvKXg-hMsRKDZKehe0Me6U',
    appId: '1:788378481654:ios:179036a49aa56d9eb68dd7',
    messagingSenderId: '788378481654',
    projectId: 'customerapp-3c30f',
    storageBucket: 'customerapp-3c30f.appspot.com',
    iosBundleId: 'com.example.customerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwxRf0hhnjKNvKXg-hMsRKDZKehe0Me6U',
    appId: '1:788378481654:ios:2231e37a356f78a5b68dd7',
    messagingSenderId: '788378481654',
    projectId: 'customerapp-3c30f',
    storageBucket: 'customerapp-3c30f.appspot.com',
    iosBundleId: 'com.example.customerapp.RunnerTests',
  );
}
